# .sops.yaml
creation_rules:
  - path_regex: .*values.yaml$
    age: age1zfx2zkjdzqpy23k9rqtmaqaghtqlzf4edj06ps00x06ct3k76gcqx6whd5
  - path_regex: .*secrets.yaml$
    age: age1zfx2zkjdzqpy23k9rqtmaqaghtqlzf4edj06ps00x06ct3k76gcqx6whd5
  - path_regex: ".*\\.yaml"
    encrypted_regex: ^(data|stringData)$
    age: age1zfx2zkjdzqpy23k9rqtmaqaghtqlzf4edj06ps00x06ct3k76gcqx6whd5
