# This file is used to set default values for helmfile
# and declare releases that are common to all environments

helmDefaults:
  kubeContext: docker-desktop
  cleanupOnFail: true          
  atomic: false
  args: []
  diffArgs: []
  verify: false # because we have unpacked local charts
  wait: true
  waitForJobs: true
  timeout: 60
  force: false
  historyMax: 0 # no limit
  createNamespace: true
  recreatePods: true
  devel: true
  skipDeps: false
  reuseValues: false
  cascade: "background"
  insecureSkipTLSVerify: false

releases:
- name: mysql-db
  namespace: mysql
  version: 9.14.1
  chart:  bitnami/mysql
  values:
  - ../mysql/values.yaml
  # Uses helm secrets plugin to decrypt the secret
  secrets: 
  - ../mysql/secrets.enc.yaml
  missingFileHandler: Error