# Default values for all releases
bases:
  - ./environments.yaml
  - ./defaults.yaml
  - ./repositories.yaml
    
commonLabels:
  kubernetes.io/managed-by: helmfile

releases:
- name: stack-io
  namespace: stack-io
  chart: ../stack-io/helmcharts/
  values:
  - ../stack-io/values.yaml
  # Uses helm secrets plugin to decrypt the secret
  secrets:
  - ../stack-io/secrets.enc.yaml
  missingFileHandler: Error
