# From the official Docker Hub MySQL page - https://hub.docker.com/_/mysql
# Uses root/root as user/password credentials
version: '3.1'

services:

  webserver:
    container_name: stack-io-webserver
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - APP_HOME=/app
        - HTTP_PORT=8080
    image: stack-io
    restart: always
    ports:
      - 8081:8080 # Expose port 8081 to the host to avoid port conflicts
    depends_on:
      - mysql
    
  mysql:
    container_name: stack-io-mysql
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: stack-io
      MYSQL_PASSWORD: stack-io
      MYSQL_DATABASE: stack-io
    volumes:
      - mysql_data:/var/lib/mysql 
      - ./mysql-init.sh:/docker-entrypoint-initdb.d/mysql-init.sh # Grants the stack-io user privileged permissions


  adminer:
    container_name: stack-io-adminer
    image: adminer
    restart: always
    ports:
      - 8082:8080 # Expose port 8082 to the host to avoid port conflicts

volumes:
  mysql_data:
    driver: local
    name: stack-io-mysql-data

networks:
  default:
    name: stack-io