# File contains default values for MySQL Helm chart
architecture: replicaset
auth:
  createDatabase: true
  database: blog
  existingSecret: "mysql-db-secret"
  # password: ""
  # replicationPassword: ""
  # replicationUser: replicator
  # rootPassword: ""
  # usePasswordFiles: false
  # username: ""
# clusterDomain: cluster.local
diagnosticMode:
  args:
  - infinity
  command:
  - sleep
  enabled: false
fullnameOverride: ""
global:
  imageRegistry: ""
  storageClass: ""
image:
  debug: false
  digest: ""
  pullPolicy: IfNotPresent
  registry: docker.io
  repository: bitnami/mysql
  tag: 8.0.35-debian-11-r0
initdbScriptsConfigMap: ""
kubeVersion: ""
metrics:
  containerSecurityContext:
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
  enabled: false
  image:
    digest: ""
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: bitnami/mysqld-exporter
    tag: 0.15.0-debian-11-r70
  livenessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 120
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  prometheusRule:
    enabled: false
    namespace: ""
  readinessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 30
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  service:
    annotations:
      prometheus.io/port: '{{ .Values.metrics.service.port }}'
      prometheus.io/scrape: "true"
    clusterIP: ""
    port: 9104
    type: ClusterIP
  serviceMonitor:
    enabled: false
    honorLabels: false
    interval: 30s
    jobLabel: ""
    namespace: ""
    scrapeTimeout: ""
nameOverride: ""
namespaceOverride: ""
networkPolicy:
  allowExternal: true
  enabled: false
primary:
  configuration: |-
    [mysqld]
    default_authentication_plugin={{- .Values.auth.defaultAuthPlugin | default "mysql_native_password" }}
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    plugin_dir=/opt/bitnami/mysql/lib/plugin
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    datadir=/bitnami/mysql/data
    tmpdir=/opt/bitnami/mysql/tmp
    max_allowed_packet=16M
    bind-address=*
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    log-error=/opt/bitnami/mysql/logs/mysqld.log
    character-set-server=UTF8
    slow_query_log=0
    long_query_time=10.0

    [client]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mysql/lib/plugin

    [manager]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
    seccompProfile:
      type: RuntimeDefault
  existingConfigmap: ""
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraFlags: ""
  livenessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  name: primary
  nodeAffinityPreset:
    key: ""
    type: ""
  pdb:
    create: false
    maxUnavailable: ""
    minAvailable: 1
  persistence:
    accessModes:
    - ReadWriteOnce
    enabled: true
    existingClaim: ""
    size: 8Gi
    storageClass: ""
    subPath: ""
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  podManagementPolicy: ""
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  priorityClassName: ""
  readinessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  runtimeClassName: ""
  schedulerName: ""
  service:
    clusterIP: ""
    externalTrafficPolicy: Cluster
    loadBalancerIP: ""
    nodePorts:
      mysql: ""
    ports:
      mysql: 3306
    sessionAffinity: None
    type: ClusterIP
  startupProbe:
    enabled: true
    failureThreshold: 10
    initialDelaySeconds: 15
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  terminationGracePeriodSeconds: ""
  updateStrategy:
    type: RollingUpdate
rbac:
  create: false
secondary:
  configuration: |-
    [mysqld]
    default_authentication_plugin=mysql_native_password
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mysql
    plugin_dir=/opt/bitnami/mysql/lib/plugin
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    datadir=/bitnami/mysql/data
    tmpdir=/opt/bitnami/mysql/tmp
    max_allowed_packet=16M
    bind-address=*
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
    log-error=/opt/bitnami/mysql/logs/mysqld.log
    character-set-server=UTF8
    slow_query_log=0
    long_query_time=10.0

    [client]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mysql/lib/plugin

    [manager]
    port=3306
    socket=/opt/bitnami/mysql/tmp/mysql.sock
    pid-file=/opt/bitnami/mysql/tmp/mysqld.pid
  containerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
      - ALL
    enabled: true
    runAsNonRoot: true
    runAsUser: 1001
    seccompProfile:
      type: RuntimeDefault
  existingConfigmap: ""
  extraEnvVarsCM: ""
  extraEnvVarsSecret: ""
  extraFlags: ""
  livenessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  name: secondary
  nodeAffinityPreset:
    key: ""
    type: ""
  pdb:
    create: false
    maxUnavailable: ""
    minAvailable: 1
  persistence:
    accessModes:
    - ReadWriteOnce
    enabled: true
    existingClaim: ""
    size: 8Gi
    storageClass: ""
    subPath: ""
  podAffinityPreset: ""
  podAntiAffinityPreset: soft
  podManagementPolicy: ""
  podSecurityContext:
    enabled: true
    fsGroup: 1001
  priorityClassName: ""
  readinessProbe:
    enabled: true
    failureThreshold: 3
    initialDelaySeconds: 5
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  replicaCount: 1
  runtimeClassName: ""
  schedulerName: ""
  service:
    clusterIP: ""
    externalTrafficPolicy: Cluster
    loadBalancerIP: ""
    nodePorts:
      mysql: ""
    ports:
      mysql: 3306
    sessionAffinity: None
    type: ClusterIP
  startupProbe:
    enabled: true
    failureThreshold: 15
    initialDelaySeconds: 15
    periodSeconds: 10
    successThreshold: 1
    timeoutSeconds: 1
  terminationGracePeriodSeconds: ""
  updateStrategy:
    type: RollingUpdate
serviceAccount:
  automountServiceAccountToken: true
  create: true
  name: ""
serviceBindings:
  enabled: false
startdbScriptsConfigMap: ""
volumePermissions:
  enabled: false
  image:
    digest: ""
    pullPolicy: IfNotPresent
    registry: docker.io
    repository: bitnami/os-shell
    tag: 11-debian-11-r90
