auth:
    rootPassword: ENC[AES256_GCM,data:+hOh1zVk0w==,iv:09FNNALvfCVYuS76WBraf8/Co2twenLYR9KGi3zpV28=,tag:+vADQ4kcFiok9XcWTxJNqQ==,type:str]
    database: ENC[AES256_GCM,data:+xL1aw==,iv:QDwRrRVsMqZ8VXIFwL8QHpa/pKPAfqBXm05jw03KYDc=,tag:HJKzuLNturIqU1a4OpgQ/Q==,type:str]
    username: ENC[AES256_GCM,data:UUxnvv9nOcI=,iv:jjgBZLr5fkqvSBSiJd4THGfp+76+L7XDApJpG1S3ra4=,tag:eJToJXJi7uSRAiqT+vIJaw==,type:str]
    password: ENC[AES256_GCM,data:Va4ZOZzIGkE=,iv:dLw9oRrZzuRchDjBTNN645cFRGwZAMhgu7u3N1w1VS0=,tag:f0BxbrAA2eXk07iyPTMIkg==,type:str]
    replicationUser: ENC[AES256_GCM,data:QJ/m6JlrADj2og==,iv:QVZjRLOCzsgk5uUHa6rtKvKHyRCoaGfgWnnq7hyCpEA=,tag:P00gDDjPL/hwkzcUkeM4+Q==,type:str]
    replicationPassword: ENC[AES256_GCM,data:yE15OWyCruY=,iv:uaILvHQWz12pOPI1qlC0IAGvWlouZzrlghnkcZd3fvc=,tag:NOLFlhhDuRxy2/jn1Ck1dw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age170kjjr9j3y2yl7etp9h7eknp9x4pxwujzvdj95k7j4xxxdags3ssdd4pdk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbjdvOTJTZEEwajFHTnBi
            bm9CVDBWVGE4dHF1YmpESVE3V3pPNlhVanlBClVqaWQ4eW1CNnVEejRwZFdsd05N
            SHVWZEhXMmtzQ2Nkcmp6RHA3UjZOZEUKLS0tIEpmZFVZdHgxTDhybGxybW9Rd1RV
            Z2JDVTBMNndqTWFKc3haS2xQL1hlR2sKqqPPrxbT+xMa8LMK/kjPwfmZeHVOSRxk
            tovPWAqnychuDMqms9oxxHhmpke8Pca2eohPl+FIdNup8Q7L4qsOGA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-06T22:35:58Z"
    mac: ENC[AES256_GCM,data:tDiCoPD/EPWy8dzDtPh0Em2H0U1l5B4zjb3ajSKxuNusNwZ8tPqvoWgzX9u/yYlUEHd4qscgGVZJ9rh+OLyRIL+15qutL+L1N81L0sJYqebOKkols39A4sNuNYns7ZGMDLKDW8jUSD4aidX/mciWX+3sw3k19CLjGrHr5GNtn/o=,iv:CKRBVGX+8f9XdsCYEDPZuVkqx+Vf5rmBCNYYq8x06as=,tag:+IANEFjsDFB2esnoHPEy7g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
