nameReference:
- kind: ConfigMap
  version: v1
  fieldSpecs:
  - path: spec/template/spec/volumes/configMap/secretName
    kind: Deployment
- kind: Secret
  version: v1
  fieldSpecs:
  - path: spec/template/spec/volumes/secret/secretName
    kind: Deployment