apiVersion: apps/v1
kind: Deployment
metadata:
  name: stack-io
  labels:
    app: stack-io
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stack-io
  template:
    metadata:
      labels:
        app: stack-io
    spec:
      initContainers:
      - name: make-executable
        image: busybox
        command: ['sh', '-c', 'cp /src/* /dst/ && chmod +x /dst/*']
        volumeMounts:
        - name: hooks-configmap
          mountPath: /src
        - name: hooks
          mountPath: /dst
      # - name: sleep
      #   image: busybox
      #   command: ['sh', '-c', 'sleep 30']
      containers:
      - name: webserver
        image: grgouveia/stack-io:latest
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "100Mi"
          limits:
            cpu: "500m"
            memory: "500Mi"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        volumeMounts:
        - name: stack-io
          mountPath: /app/server.confi
          subPath: server.confi # Using subPath to mount a single file from a volume
        - name: hooks
          mountPath: /app/hooks
        lifecycle:
          postStart:
            httpGet:
              path: /notify-start
              port: 8080
          preStop:
            exec:
              command: ["/bin/sh","-c","/app/hooks/pre-stop-hook.sh"]
      volumes:
      - name: stack-io
        secret:
          secretName: stack-io
          items:
          - key: server.confi
            path: server.confi
      - name: hooks-configmap
        configMap:
          name: stack-io
      - name: hooks
        emptyDir: {}
      