helmCharts:
- name: mysql
  repo: oci://registry-1.docker.io/bitnamicharts
  version: 9.14.1
  releaseName: mysql
  namespace: mysql
  valuesFile: ./values.yaml
  additionalValuesFiles:
    - "./secrets.enc.yaml"
  includeCRDs: true
